"""Conversation states enum."""
from enum import Enum


class OrderStates(Enum):
    """States for the order conversation flow."""
    ENTRY_POINT = 1
    EDITING = 2
    EDITING_ITEM = 3
    ENTERING_EDIT_QTY = 4
    CHOOSING_CAT = 5
    CHOOSING_ITEM = 6
    ENTERING_QTY = 7
    CHOOSING_HISTORY = 8
    ENTERING_HISTORY_DATE = 9
    CONFIRM_ORDER = 10
    ENTERING_DATE = 11
    ENTERING_TEMPLATE_NAME = 12

    # Non-food flow states
    NONFOOD_ENTRY_POINT = 13
    NONFOOD_EDITING = 14
    NONFOOD_EDITING_ITEM = 15
    NONFOOD_ENTERING_EDIT_QTY = 16
    NONFOOD_CHOOSING_CAT = 17
    NONFOOD_CHOOSING_ITEM = 18
    NONFOOD_ENTERING_QTY = 19
    NONFOOD_CHOOSING_HISTORY = 20
    NONFOOD_ENTERING_HISTORY_DATE = 21
    NONFOOD_CONFIRM_ORDER = 22
    NONFOOD_ENTERING_DATE = 23
    NONFOOD_ENTERING_TEMPLATE_NAME = 24
    NONFOOD_SEARCHING = 25
